language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a

android:
  components:
    - tool
    - android-24      
    - build-tools-23.0.2
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21
    - extra


before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: cd MakeAFocalpoint/ && ./gradlew build 
